/**
 * Kroger product IDs whose photo is Kroger's blank placeholder. Generated by
 * scripts/find-blank-kroger-photos.mjs; do not edit by hand.
 */
export const BLANK_KROGER_PHOTOS: ReadonlySet<string> = new Set([
  '0003700012432',
  '0003700012433',
  '0003700054825',
  '0003700080091',
  '0003700080819',
  '0003700080831',
]);
