// Keeps the design tokens in sync.
//
//   packages/tokens/tokens.json  (source of truth)
//        │  checked by `check`
//        ▼
//   packages/tokens/tokens.css   (hand-derived, kept verbatim from the design system)
//        │  generated by `sync`, verified by `check`
//        ▼
//   apps/extension/src/content/tokens.ts   (CSS as a string for the Shadow DOM)
//
// Usage: node scripts/tokens.mjs <sync|check>
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = new URL('../', import.meta.url);
const cssPath = new URL('packages/tokens/tokens.css', root);
const jsonPath = new URL('packages/tokens/tokens.json', root);
const extensionPath = new URL('apps/extension/src/content/tokens.ts', root);

/** The extension's bundler-free build cannot `import '...?raw'`, so the CSS is embedded. */
function renderExtensionModule(css) {
  const escaped = css.replaceAll('\\', '\\\\').replaceAll('`', '\\`').replaceAll('${', '\\${');
  return `// GENERATED from packages/tokens/tokens.css by scripts/tokens.mjs. Do not edit by hand.
// Run \`pnpm run tokens:sync\` after changing the tokens; \`pnpm run tokens:check\` fails on drift.
//
// The badge renders in a Shadow DOM and cannot inherit page CSS, so this string is injected
// into the shadow root's own <style> (see ./shadow-root.ts). If the extension moves to a
// bundler, replace this file with \`import TOKENS_CSS from '<path>/tokens.css?raw'\`.
export const TOKENS_CSS = \`${escaped}\`;
`;
}

/** Custom property names declared in the CSS, e.g. "surface-100". */
function declaredProperties(css) {
  return new Set([...css.matchAll(/--([a-z0-9-]+)\s*:/g)].map((match) => match[1]));
}

function declaredValue(css, name) {
  const match = css.match(new RegExp(`--${name}\\s*:\\s*([^;]+);`));
  return match?.[1]?.trim();
}

/** A style's declarations from `.name { ... }`, or undefined if the class is missing. */
function ruleBody(css, className) {
  return css.match(new RegExp(`\\.${className}\\s*\\{([^}]*)\\}`))?.[1];
}

function checkJsonMatchesCss(json, css) {
  const problems = [];
  const expected = new Set();

  const expectValue = (name, value) => {
    expected.add(name);
    // JSON aliases like "{surface-900}" are written as var(--surface-900) in CSS.
    const wanted = /^\{(.+)\}$/.test(value) ? `var(--${value.slice(1, -1)})` : value;
    const actual = declaredValue(css, name);
    if (actual !== wanted) {
      problems.push(`--${name}: tokens.css has ${actual ?? 'nothing'}, tokens.json says ${wanted}`);
    }
  };

  for (const token of json.color.tokens) expectValue(token.name, token.value);
  for (const token of json.spacing.tokens) expectValue(token.name, token.value);
  for (const token of json.radius.tokens) expectValue(token.name, token.value);
  for (const [family, stack] of Object.entries(json.type.families)) {
    expectValue(`font-${family}`, stack);
  }

  for (const style of json.type.groups.flatMap((group) => group.styles)) {
    const body = ruleBody(css, style.name);
    const wanted = {
      'font-size': style.fontSize,
      'line-height': style.lineHeight,
      'font-weight': String(style.fontWeight),
      ...(style.letterSpacing ? { 'letter-spacing': style.letterSpacing } : {}),
    };
    if (!body) {
      problems.push(`.${style.name}: class is missing from tokens.css`);
      continue;
    }
    for (const [property, value] of Object.entries(wanted)) {
      if (!new RegExp(`${property}\\s*:\\s*${value.replaceAll('.', '\\.')}\\s*;`).test(body)) {
        problems.push(`.${style.name}: tokens.css does not set ${property}: ${value}`);
      }
    }
  }

  for (const name of declaredProperties(css)) {
    if (!expected.has(name)) problems.push(`--${name}: in tokens.css but not in tokens.json`);
  }
  return problems;
}

async function main(command) {
  const css = await readFile(cssPath, 'utf8');
  const generated = renderExtensionModule(css);

  if (command === 'sync') {
    await writeFile(extensionPath, generated);
    console.log(`Wrote ${fileURLToPath(extensionPath)}`);
    return;
  }

  if (command !== 'check') {
    console.error('Usage: node scripts/tokens.mjs <sync|check>');
    process.exitCode = 2;
    return;
  }

  const problems = checkJsonMatchesCss(JSON.parse(await readFile(jsonPath, 'utf8')), css);
  const current = await readFile(extensionPath, 'utf8').catch(() => undefined);
  if (current !== generated) {
    problems.push(
      'apps/extension/src/content/tokens.ts is out of date with packages/tokens/tokens.css ' +
        '(run `pnpm run tokens:sync`)',
    );
  }

  if (problems.length > 0) {
    console.error(`Token check failed (${problems.length} issue(s)):`);
    problems.forEach((problem) => console.error(`- ${problem}`));
    process.exitCode = 1;
    return;
  }
  console.log('Token check passed: tokens.json, tokens.css, and the extension copy agree.');
}

await main(process.argv[2]);
